name: Publish Docker image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #6.0.1
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 #5.10.0
        with:
          images: ghcr.io/yoshinorin/docker-qualtet
      -
        name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #6.18.0
        with:
          context: ./docker
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
